# Generated by Django 3.1.3 on 2020-11-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_client_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user_id',
            new_name='user',
        ),
    ]
