# Generated by Django 3.1.3 on 2020-11-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_auto_20201106_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='next_pin',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
