# Generated by Django 3.1.3 on 2020-11-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_auto_20201117_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='earliest_visit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='worktime',
            name='latest_visit',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='end_time',
            field=models.TimeField(default='16:00'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='start_time',
            field=models.TimeField(default='8:00'),
        ),
    ]
