# Generated by Django 3.1.3 on 2020-11-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_auto_20201118_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
