# Generated by Django 3.1.3 on 2020-11-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_auto_20201128_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='is_avaible',
            new_name='is_available',
        ),
    ]
