# Generated by Django 3.1.3 on 2020-11-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_auto_20201128_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='stop',
            field=models.DateTimeField(),
        ),
    ]
