# Generated by Django 3.1.3 on 2020-12-03 21:00

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_auto_20201128_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[userapp.models.Client.only_digits]),
        ),
    ]
