# Generated by Django 3.1.4 on 2020-12-10 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_auto_20201203_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='end_time',
        ),
        migrations.AddField(
            model_name='worktime',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
