# Generated by Django 3.1.4 on 2020-12-11 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_auto_20201210_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktime',
            old_name='duration',
            new_name='duration_monday',
        ),
        migrations.RenameField(
            model_name='worktime',
            old_name='start_time',
            new_name='start_monday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='worktime',
            name='duration_friday',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='duration_saturday',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='duration_sunday',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='duration_thursday',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='duration_tuesday',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='duration_wednesday',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='start_friday',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='start_saturday',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='start_sunday',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='start_thursday',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='start_tuesday',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='start_wednesday',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
