# Generated by Django 3.1.4 on 2020-12-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='site_url',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
