# Generated by Django 3.1.5 on 2021-01-15 00:13

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_auto_20201215_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[userapp.models.UserSettings.only_digits]),
        ),
    ]
