# Generated by Django 3.1.5 on 2021-01-19 14:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0027_usersettings_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='duration_friday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='duration_monday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='duration_saturday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='duration_sunday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='duration_thursday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='duration_tuesday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='duration_wednesday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='earliest_visit',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='holidays',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='latest_visit',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='start_friday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='start_monday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='start_saturday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='start_sunday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='start_thursday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='start_tuesday',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='start_wednesday',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='earliest_visit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='holidays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='latest_visit',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='worktime',
            name='day_of_week',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worktime',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='worktime',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
