# Generated by Django 3.1.5 on 2021-01-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_auto_20210119_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
