# Generated by Django 3.1.5 on 2021-01-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0029_worktime_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='is_active',
        ),
    ]
