# Generated by Django 3.1.5 on 2021-01-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0031_timeoff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktime',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='worktime',
            old_name='start_time',
            new_name='start',
        ),
    ]
