# Generated by Django 3.1.5 on 2021-01-19 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0032_auto_20210119_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='end',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='start',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
