# Generated by Django 3.1.5 on 2021-01-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0033_auto_20210119_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
