# Generated by Django 3.1.5 on 2021-01-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0034_auto_20210121_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='end',
            field=models.DurationField(default=''),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='start',
            field=models.DurationField(default=''),
        ),
    ]
