# Generated by Django 3.1.3 on 2020-11-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeszyt', '0002_auto_20201106_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='description',
            new_name='surname',
        ),
    ]
