# Generated by Django 3.1.3 on 2020-11-06 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zeszyt', '0007_auto_20201106_2020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('user', 'phone_number')},
        ),
    ]
